calibration:
  area_low_ratio: 0.45
  area_up_ratio: 0.45
  hue_margin: 10
  max_area: 393
  min_area: 149
  preset: wide
  red_lower_1:
  - 0
  - 150
  - 23
  red_lower_2:
  - 170
  - 150
  - 23
  red_upper_1:
  - 10
  - 255
  - 143
  red_upper_2:
  - 180
  - 255
  - 143
  sat_margin: 60
  val_margin: 60
force_node:
  force_magnitude: 0.0
  node_number: 1
hough_circles:
  dp: 1
  max_radius: 20
  min_dist: 10
  min_radius: 7
  param1: 20
  param2: 9
presets:
  wide:
    red_lower_1:
    - 0
    - 40
    - 30
    red_lower_2:
    - 170
    - 40
    - 30
    red_upper_1:
    - 10
    - 255
    - 255
    red_upper_2:
    - 180
    - 255
    - 255
