calibration:
  area_low_ratio: 0.45
  area_up_ratio: 0.45
  hue_margin: 10
  max_area: 1421
  min_area: 539
  preset: wide
  red_lower_1:
  - 168
  - 157
  - 103
  red_lower_2:
  - 0
  - 157
  - 103
  red_upper_1:
  - 180
  - 255
  - 223
  red_upper_2:
  - 8
  - 255
  - 223
  sat_margin: 60
  val_margin: 60
hough_circles:
  dp: 1
  max_radius: 20
  min_dist: 40
  min_radius: 2
  param1: 200
  param2: 15
presets:
  wide:
    red_lower_1:
    - 0
    - 40
    - 30
    red_lower_2:
    - 170
    - 40
    - 30
    red_upper_1:
    - 10
    - 255
    - 255
    red_upper_2:
    - 180
    - 255
    - 255
